Description: FSI DataZone Demo

Resources:
  
  S3Bucket:
    Type: AWS::S3::Bucket

  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: 'data-zone-cloud9'
      Description: 'Cloud9 development enviorment'
      ImageId: 'amazonlinux-2-x86_64'
      InstanceType: 't2.large'
      AutomaticStopTimeMinutes: '30'
      Repositories: [
        {
          "PathComponent" : '/DataZone_Demo_FSI',
          "RepositoryUrl" : 'https://github.com/ev2900/DataZone_Demo_FSI.git'
        }
      ]

  GlueCrawlerIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'Glue_Crawler_IAM_Role'
      Description: 'IAM role for Glue Crawler'
      # Trust relationships
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      # Premissions
      Policies:
        - PolicyName: LakeFormation_GetDataAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: '*'
        - PolicyName: S3_Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'lakeformation:GetDataAccess'
                Resource: '*'
        - PolicyName: AWS_GlueServiceRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'glue:*'
                  - 's3:GetBucketLocation'
                  - 's3:ListBucket'
                  - 's3:ListAllMyBuckets'
                  - 's3:GetBucketAcl'
                  - 'ec2:DescribeVpcEndpoints'
                  - 'ec2:DescribeRouteTables'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeVpcAttribute'
                  - 'iam:ListRolePolicies'
                  - 'iam:GetRole'
                  - 'iam:GetRolePolicy'
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
              - Effect: Allow
                Action: 's3:CreateBucket'
                Resource: 'arn:aws:s3:::aws-glue-*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource: 
                  - 'arn:aws:s3:::aws-glue-*/*'
                  - 'arn:aws:s3:::*/*aws-glue-*/*'
              - Effect: Allow
                Action: 's3:GetObject'
                Resource: 
                  - 'arn:aws:s3:::crawler-public*'
                  - 'arn:aws:s3:::aws-glue-*'
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*:/aws-glue/*'
              - Effect: Allow
                Action: 
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                Resource: 
                  - 'arn:aws:ec2:*:*:network-interface/*'
                  - 'arn:aws:ec2:*:*:security-group/*'
                  - 'arn:aws:ec2:*:*:instance/*'
